service:
  name: image-crop

provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-2
  memorySize: 3008

functions:
  CropImage:
    handler: main.uploadImage
    timeout: 360
    events:
      - http:
          method: post
          path: uploadImage
          cors: true
    package:
      include:
        - main.ts
      exclude:
        - node_modules/**
